### ISSUE TITLE
undefined: oauthToken

### ISSUE THREAD

**Issue by dbluxo** [csmarchbanks/stravaql#1]
Hi @csmarchbanks 👋 ,

I wanted to run the app, I exported the two env variables before, but I get the following errors:

```
./main.go:44:17: undefined: oauthToken
./main.go:46:19: undefined: newActivitySummaryCache
./main.go:65:28: undefined: newQueryable
```

Any ideas?

**Comment by csmarchbanks** [comment]
Hmm, all of those should be defined, that is interesting error. I just tried pulling a clean version and do not run into these errors. What commands are you running to build stravaql? It almost sounds like some of the files were deleted or something from your repo.
